targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      freezed:
        options:
          make_collections_unmodifiable: false
    sources:
      - $package$
      - lib/**
      - stories/**